const Images =
{
    AH: { uri: require('./cards/AH.png') },
    AD: { uri: require('./cards/AD.png') },
    AC: { uri: require('./cards/AC.png') },
    AS: { uri: require('./cards/AS.png') },
    "2H": { uri: require('./cards/2H.png') },
    "2D": { uri: require('./cards/2D.png') },
    "2C": { uri: require('./cards/2C.png') },
    "2S": { uri: require('./cards/2S.png') },
    "3H": { uri: require('./cards/3H.png') },
    "3D": { uri: require('./cards/3D.png') },
    "3C": { uri: require('./cards/3C.png') },
    "3S": { uri: require('./cards/3S.png') },
    "4H": { uri: require('./cards/4H.png') },
    "4D": { uri: require('./cards/4D.png') },
    "4C": { uri: require('./cards/4C.png') },
    "4S": { uri: require('./cards/4S.png') },
    "5H": { uri: require('./cards/5H.png') },
    "5D": { uri: require('./cards/5D.png') },
    "5C": { uri: require('./cards/5C.png') },
    "5S": { uri: require('./cards/5S.png') },
    "6H": { uri: require('./cards/6H.png') },
    "6D": { uri: require('./cards/6D.png') },
    "6C": { uri: require('./cards/6C.png') },
    "6S": { uri: require('./cards/6S.png') },
    "7H": { uri: require('./cards/7H.png') },
    "7D": { uri: require('./cards/7D.png') },
    "7C": { uri: require('./cards/7C.png') },
    "7S": { uri: require('./cards/7S.png') },
    "8H": { uri: require('./cards/8H.png') },
    "8D": { uri: require('./cards/8D.png') },
    "8C": { uri: require('./cards/8C.png') },
    "8S": { uri: require('./cards/8S.png') },
    "9H": { uri: require('./cards/9H.png') },
    "9D": { uri: require('./cards/9D.png') },
    "9C": { uri: require('./cards/9C.png') },
    "9S": { uri: require('./cards/9S.png') },
    "10H": { uri: require('./cards/10H.png') },
    "10D": { uri: require('./cards/10D.png') },
    "10C": { uri: require('./cards/10C.png') },
    "10S": { uri: require('./cards/10S.png') },
    "JH": { uri: require('./cards/JH.png') },
    "JD": { uri: require('./cards/JD.png') },
    "JC": { uri: require('./cards/JC.png') },
    "JS": { uri: require('./cards/JS.png') },
    "QH": { uri: require('./cards/QH.png') },
    "QD": { uri: require('./cards/QD.png') },
    "QC": { uri: require('./cards/QC.png') },
    "QS": { uri: require('./cards/QS.png') },
    "KH": { uri: require('./cards/KH.png') },
    "KD": { uri: require('./cards/KD.png') },
    "KC": { uri: require('./cards/KC.png') },
    "KS": { uri: require('./cards/KS.png') },
}

export default Images;